#! /usr/bin/env fish

echo "Purging command line history..."

history delete --contains "SHARED"
history delete --contains "ping"
history delete --contains "youtube."
history delete --contains "google."

echo "Destroying browser history..."

rm -rf /Users/workstation/Library/Caches/Safari
rm -rf /Users/workstation/Library/Safari/History*
touch /Users/workstation/Library/Caches/Safari

echo "Emptying trash..."

rm -rf /Users/workstation/.Trash/*

echo "Starting streaming apps..."

open /Applications/OBS.app
sleep 1
open /Applications/Spotify.app
sleep 1
open /Applications/Safari.app
